/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeOTP */

#ifndef _Included_NativeOTP
#define _Included_NativeOTP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeOTP
 * Method:    one_time_pad
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_NativeOTP_one_1time_1pad
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
